$schema: 
  https://azuremlschemas.azureedge.net/promptflow/latest/AzureOpenAIConnection.schema.json
type: azure_open_ai
name: open_ai_connection
module: promptflow.connections
api_base: https://open-ai-olonok.openai.azure.com/
api_key: ${env:OPEN_AI_CONNECTION_API_KEY}
api_type: azure
api_version: 2024-02-15-preview
auth_mode: key
