services:
  mysql:
    image: mariadb:10.3
    container_name: mariadb
    hostname: mariadb
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT1}:3306
      - ${MYSQL_PORT2}:33060
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/password1
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - password1
      - password2
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/password1
    secrets:
      - password1
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - network

  mlflow:
    image: Cambiame.azurecr.io/detectai-mlflow:latest
    container_name: mlflow_tracker
    hostname: mlflow_tracker
    build:
      args:
        mlflow_user: ${USER_MLFLOW}
    depends_on:
      - mysql
    env_file:                                
      - .env
      - .secrets/env-secrets
    ports:
      - ${MLFLOW_PORT}:5000
    volumes:
      - /home/${USER_MLFLOW}/mlflow/mlruns:/home/${USER_MLFLOW}/mlflow/mlruns
    networks:
      - network

  custom_classifier:
    container_name: custom_classifier
    image: Cambiame.azurecr.io/detectai-custom_classifier:latest
    hostname: custom_classifier        
    ports:
      - 5020:5020
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    restart: always
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    volumes:
      - ../docker/configs/nginx/nginx-local.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - mysql
      - phpmyadmin
      - mlflow
      - custom_classifier
    restart: always
    networks:
      - network

volumes:
  database_volume:

secrets:
  password1:
    file: ./.secrets/mysql-root-password.txt
  password2:
    file: ./.secrets/mysql-mlflowuser-password.txt

networks:
  network:
